# Generated by Django 4.1.4 on 2023-12-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='i',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='card',
            name='n',
            field=models.IntegerField(default=0, max_length=200),
        ),
    ]
