# Generated by Django 4.1.4 on 2023-12-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0002_card_i_card_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
    ]
