# Generated by Django 4.1.4 on 2024-02-22 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0003_card_learnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
