# Generated by Django 4.1.4 on 2024-02-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0004_card_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='constant_i',
            field=models.FloatField(default=2.5),
        ),
    ]
