# Generated by Django 4.1.4 on 2024-02-22 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0005_card_constant_i'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.date(2024, 2, 22)),
        ),
    ]
