# Generated by Django 4.1.4 on 2024-02-25 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0006_alter_card_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='review_n',
            field=models.IntegerField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='card',
            name='review_date',
            field=models.DateField(default=datetime.date(2024, 2, 25)),
        ),
    ]
