# Generated by Django 4.1.4 on 2024-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srs', '0007_card_review_n_alter_card_review_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='review_n',
        ),
    ]
